export const styles = {
  editableDiv: {
    resize: "none",
    overflow: "hidden",
    padding: "10px 12px",
    fontSize: "16px",
    lineHeight: "1.6",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    outline: "none",
    backgroundColor: "#fff",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.08)",
    whiteSpace: "pre-wrap",
    wordWrap: "break-word",
    minHeight: "36px",
    cursor: "text",
    transition: "border-color 0.3s ease, box-shadow 0.3s ease",
  },
  editableDivFocus: {
    borderColor: "#2563eb",
    boxShadow: "0 4px 8px rgba(37, 99, 235, 0.2)",
  },
  code: {
    valid: {
      color: "#344fcd",
      margin: "2px 1px",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 700,
      padding: "4px 8px",
      borderRadius: "4px",
      border: "1px solid #ccd6e3",
      fontSize: "14px",
      display: "inline-block",
      whiteSpace: "nowrap",
      backgroundColor: "#f0f4ff",
    },
    invalid: {
      background: "linear-gradient(135deg, #ffeded, #ffd6d6)",
      color: "#d32f2f",
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 700,
      padding: "4px 8px",
      borderRadius: "4px",
      border: "1px solid #e57373",
      fontSize: "14px",
      display: "inline-block",
      whiteSpace: "nowrap",
    },
  },
  error: {
    marginTop: "8px",
    color: "#d32f2f",
    fontSize: "14px",
    fontWeight: "500",
    fontFamily: "'Roboto', sans-serif",
    letterSpacing: "0.4px",
    textAlign: "left",
  },
};
